# Generated by Django 5.2.13 on 2026-06-12 05:56

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.AutoField(db_column='id_registro_pendiente', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='correo', db_index=True, max_length=254)),
                ('first_name', models.CharField(db_column='nombre', max_length=150)),
                ('password_hash', models.CharField(db_column='hash_contrasena', help_text='Contraseña hasheada con django.contrib.auth.hashers.make_password.', max_length=128)),
                ('code', models.CharField(db_column='codigo', db_index=True, max_length=6)),
                ('token', models.CharField(db_column='token', db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('expires_at', models.DateTimeField(db_column='expira_en')),
                ('used_at', models.DateTimeField(blank=True, db_column='usado_en', null=True)),
                ('attempts', models.PositiveSmallIntegerField(db_column='intentos', default=0, help_text='Cuántas veces se intentó verificar (anti brute-force).')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'verbose_name': 'Registro pendiente',
                'verbose_name_plural': 'Registros pendientes',
                'db_table': 'tbl_registro_pendiente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.AutoField(db_column='id_codigo_verificacion', primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('register', 'Verificación de registro'), ('delete_account', 'Confirmar eliminación de cuenta')], db_column='proposito', db_index=True, default='register', help_text='Para qué acción se usa este código.', max_length=20)),
                ('code', models.CharField(db_column='codigo', db_index=True, max_length=6)),
                ('token', models.CharField(db_column='token', db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('expires_at', models.DateTimeField(db_column='expira_en')),
                ('used_at', models.DateTimeField(blank=True, db_column='usado_en', null=True)),
                ('attempts', models.PositiveSmallIntegerField(db_column='intentos', default=0, help_text='Cuántas veces se intentó verificar este código (anti brute-force).')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de verificación',
                'verbose_name_plural': 'Códigos de verificación',
                'db_table': 'tbl_codigo_verificacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(db_column='id_token_recuperacion', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token', db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('expires_at', models.DateTimeField(db_column='expira_en')),
                ('used_at', models.DateTimeField(blank=True, db_column='usado_en', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='direccion_ip', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de recuperación',
                'verbose_name_plural': 'Tokens de recuperación',
                'db_table': 'tbl_token_recuperacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(db_column='id_perfil_usuario', primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, db_column='avatar', help_text='Foto de perfil. Si está vacío se usa avatar por defecto (iniciales).', null=True, upload_to=apps.accounts.models._avatar_upload_path)),
                ('forward_safe_emails', models.BooleanField(db_column='reenviar_correos_seguros', default=False, help_text='Reenviar correos seguros al correo real del usuario.')),
                ('email_verified', models.BooleanField(db_column='correo_verificado', default=False)),
                ('alias_quota_extra', models.IntegerField(db_column='cupo_alias_extra', default=0, help_text='Ajuste de cupo de alias (positivo o negativo).')),
                ('alias_unlimited', models.BooleanField(db_column='alias_ilimitados', default=False, help_text='Concede al usuario alias ilimitados sin volverlo admin.')),
                ('last_toast_notif_id', models.PositiveBigIntegerField(db_column='ultimo_toast_id', default=0, help_text='ID máximo de notificación cuyo toast ya se mostró.')),
                ('is_deleted', models.BooleanField(db_column='eliminado', default=False, help_text='Soft delete: marca la cuenta como eliminada sin borrar los datos.')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='eliminado_en', help_text='Cuándo se marcó la cuenta como eliminada.', null=True)),
                ('deletion_ip', models.GenericIPAddressField(blank=True, db_column='ip_eliminacion', help_text='IP desde donde se solicitó la eliminación.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('user', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='AccountLock',
            fields=[
                ('id', models.AutoField(db_column='id_bloqueo_cuenta', primary_key=True, serialize=False)),
                ('failed_login_attempts', models.PositiveIntegerField(db_column='intentos_fallidos', default=0, help_text='Intentos consecutivos de password incorrecta. Se resetea al login exitoso.')),
                ('temp_locked_until', models.DateTimeField(blank=True, db_column='bloqueo_temp_hasta', help_text='Si > now, la cuenta está bloqueada temporalmente.', null=True)),
                ('temp_lock_triggered', models.BooleanField(db_column='bloqueo_temp_activado', default=False, help_text='True una vez que se disparó el temp lock. La siguiente falla = bloqueo permanente.')),
                ('permanent_lock_reason', models.TextField(blank=True, db_column='motivo_bloqueo_perm', default='', help_text='Motivos que se muestran al usuario en la card de cuenta bloqueada.')),
                ('permanent_lock_at', models.DateTimeField(blank=True, db_column='bloqueo_perm_en', help_text='Cuándo se bloqueó permanentemente la cuenta por intentos fallidos.', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('profile', models.OneToOneField(db_column='id_perfil_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_bloqueo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(db_column='id_sesion_usuario', primary_key=True, serialize=False)),
                ('current_session_key', models.CharField(blank=True, db_column='sesion_actual', default='', help_text='Session key activa. Cualquier otra sesión del usuario será cerrada.', max_length=40)),
                ('session_last_activity', models.DateTimeField(blank=True, db_column='ultima_actividad_sesion', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('profile', models.OneToOneField(db_column='id_perfil_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='session', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_sesion_usuario',
            },
        ),
        migrations.CreateModel(
            name='AccountRecoveryRequest',
            fields=[
                ('id', models.AutoField(db_column='id_solicitud_recuperacion', primary_key=True, serialize=False)),
                ('reason', models.TextField(db_column='motivo', help_text='Explicación del usuario de por qué quiere recuperar la cuenta.')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_column='estado', default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, db_column='nota_admin', help_text='Nota del admin al aprobar/rechazar (opcional).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('resolved_at', models.DateTimeField(blank=True, db_column='resuelto_en', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('resolved_by', models.ForeignKey(blank=True, db_column='id_resuelto_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_account_recovery_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='account_recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de recuperación de cuenta',
                'verbose_name_plural': 'Solicitudes de recuperación de cuenta',
                'db_table': 'tbl_solicitud_recuperacion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tbl_solicit_estado_7b2f93_idx'), models.Index(fields=['user', '-created_at'], name='tbl_solicit_id_usua_0eb849_idx')],
            },
        ),
    ]
