# Generated by Django 5.2.13 on 2026-06-12 05:57

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlock',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(db_column='bqc_intentos_fallidos', default=0, help_text='Intentos consecutivos de password incorrecta. Se resetea al login exitoso.'),
        ),
        migrations.AlterField(
            model_name='accountlock',
            name='is_active',
            field=models.BooleanField(db_column='bqc_activo', default=True),
        ),
        migrations.AlterField(
            model_name='accountlock',
            name='permanent_lock_at',
            field=models.DateTimeField(blank=True, db_column='bqc_bloqueo_perm_en', help_text='Cuándo se bloqueó permanentemente la cuenta por intentos fallidos.', null=True),
        ),
        migrations.AlterField(
            model_name='accountlock',
            name='permanent_lock_reason',
            field=models.TextField(blank=True, db_column='bqc_motivo_bloqueo_perm', default='', help_text='Motivos que se muestran al usuario en la card de cuenta bloqueada.'),
        ),
        migrations.AlterField(
            model_name='accountlock',
            name='temp_lock_triggered',
            field=models.BooleanField(db_column='bqc_bloqueo_temp_activado', default=False, help_text='True una vez que se disparó el temp lock. La siguiente falla = bloqueo permanente.'),
        ),
        migrations.AlterField(
            model_name='accountlock',
            name='temp_locked_until',
            field=models.DateTimeField(blank=True, db_column='bqc_bloqueo_temp_hasta', help_text='Si > now, la cuenta está bloqueada temporalmente.', null=True),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='admin_note',
            field=models.TextField(blank=True, db_column='sre_nota_admin', help_text='Nota del admin al aprobar/rechazar (opcional).'),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='sre_creado_en'),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='is_active',
            field=models.BooleanField(db_column='sre_activo', default=True),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='reason',
            field=models.TextField(db_column='sre_motivo', help_text='Explicación del usuario de por qué quiere recuperar la cuenta.'),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_column='sre_resuelto_en', null=True),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_column='sre_estado', default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(db_column='cdv_intentos', default=0, help_text='Cuántas veces se intentó verificar este código (anti brute-force).'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(db_column='cdv_codigo', db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cdv_creado_en'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(db_column='cdv_expira_en'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='is_active',
            field=models.BooleanField(db_column='cdv_activo', default=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Verificación de registro'), ('delete_account', 'Confirmar eliminación de cuenta')], db_column='cdv_proposito', db_index=True, default='register', help_text='Para qué acción se usa este código.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='token',
            field=models.CharField(db_column='cdv_token', db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, db_column='cdv_usado_en', null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='tkr_creado_en'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(db_column='tkr_expira_en'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='tkr_direccion_ip', null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='is_active',
            field=models.BooleanField(db_column='tkr_activo', default=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_column='tkr_token', db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, db_column='tkr_usado_en', null=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='attempts',
            field=models.PositiveSmallIntegerField(db_column='rgp_intentos', default=0, help_text='Cuántas veces se intentó verificar (anti brute-force).'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='code',
            field=models.CharField(db_column='rgp_codigo', db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='rgp_creado_en'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(db_column='rgp_correo', db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(db_column='rgp_expira_en'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='first_name',
            field=models.CharField(db_column='rgp_nombre', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='is_active',
            field=models.BooleanField(db_column='rgp_activo', default=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='password_hash',
            field=models.CharField(db_column='rgp_hash_contrasena', help_text='Contraseña hasheada con django.contrib.auth.hashers.make_password.', max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='token',
            field=models.CharField(db_column='rgp_token', db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='used_at',
            field=models.DateTimeField(blank=True, db_column='rgp_usado_en', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alias_quota_extra',
            field=models.IntegerField(db_column='pfu_cupo_alias_extra', default=0, help_text='Ajuste de cupo de alias (positivo o negativo).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alias_unlimited',
            field=models.BooleanField(db_column='pfu_alias_ilimitados', default=False, help_text='Concede al usuario alias ilimitados sin volverlo admin.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, db_column='pfu_avatar', help_text='Foto de perfil. Si está vacío se usa avatar por defecto (iniciales).', null=True, upload_to=apps.accounts.models._avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='pfu_eliminado_en', help_text='Cuándo se marcó la cuenta como eliminada.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deletion_ip',
            field=models.GenericIPAddressField(blank=True, db_column='pfu_ip_eliminacion', help_text='IP desde donde se solicitó la eliminación.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(db_column='pfu_correo_verificado', default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='forward_safe_emails',
            field=models.BooleanField(db_column='pfu_reenviar_correos_seguros', default=False, help_text='Reenviar correos seguros al correo real del usuario.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_column='pfu_activo', default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(db_column='pfu_eliminado', default=False, help_text='Soft delete: marca la cuenta como eliminada sin borrar los datos.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_toast_notif_id',
            field=models.PositiveBigIntegerField(db_column='pfu_ultimo_toast_id', default=0, help_text='ID máximo de notificación cuyo toast ya se mostró.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='pfu_actualizado_en'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='current_session_key',
            field=models.CharField(blank=True, db_column='ssu_sesion_actual', default='', help_text='Session key activa. Cualquier otra sesión del usuario será cerrada.', max_length=40),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_column='ssu_activo', default=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_last_activity',
            field=models.DateTimeField(blank=True, db_column='ssu_ultima_actividad_sesion', null=True),
        ),
    ]
