# Generated by Django 5.2.13 on 2026-05-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias_quota_extra',
            field=models.PositiveIntegerField(default=0, help_text='Cupo extra de alias concedido por administradores.'),
        ),
    ]
