# Generated by Django 5.2.7 on 2026-06-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_tbl_solicit_estado_7b2f93_idx_tbl_solicit_sre_est_b3ee15_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Los índices ya existen en BD con los nombres correctos,
            # no necesitamos ejecutar SQL.
            "SELECT 1;",
            elidable=True,
            state_operations=[
                migrations.RenameIndex(
                    model_name='accountrecoveryrequest',
                    new_name='accounts_ac_status_7da5c4_idx',
                    old_name='tbl_solicit_estado_7b2f93_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            "SELECT 1;",
            elidable=True,
            state_operations=[
                migrations.RenameIndex(
                    model_name='accountrecoveryrequest',
                    new_name='accounts_ac_user_id_768d59_idx',
                    old_name='tbl_solicit_id_usua_0eb849_idx',
                ),
            ],
        ),
    ]
