# Generated by Django 5.2.13 on 2026-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_alias_quota_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alias_quota_extra',
            field=models.IntegerField(default=0, help_text='Ajuste de cupo de alias (positivo o negativo).'),
        ),
    ]
