# Generated by Django 5.2.13 on 2026-05-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_alias_quota_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias_unlimited',
            field=models.BooleanField(default=False, help_text='Concede al usuario alias ilimitados sin volverlo admin.'),
        ),
    ]
