# Generated by Django 5.2.7 on 2026-06-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_tbl_solicit_estado_7b2f93_idx_accounts_ac_status_7da5c4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='malicious_attachment_attempts',
            field=models.IntegerField(db_column='pfu_intentos_adjunto_malicioso', default=0, help_text='Contador de intentos de adjuntar malware en correos salientes. Se reinicia al llegar a 0 tras bloqueo manual del admin.'),
        ),
    ]
