# Generated by Django 5.2.13 on 2026-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_alias_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_toast_notif_id',
            field=models.PositiveBigIntegerField(default=0, help_text='ID máximo de notificación cuyo toast ya se mostró.'),
        ),
    ]
