# Generated by Django 5.2.7 on 2026-06-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_malicious_attachment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='malicious_attempt_data',
            field=models.JSONField(blank=True, db_column='pfu_datos_intento_malicioso', default=dict, help_text='Almacena detalles del primer intento de malware (filename, threat, score, timestamp). Se lee al segundo intento para notificar al admin con ambos, luego se limpia.'),
        ),
    ]
