# Generated by Django 5.2.13 on 2026-05-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_last_toast_notif_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Verificación de registro'), ('delete_account', 'Confirmar eliminación de cuenta')], db_index=True, default='register', help_text='Para qué acción se usa este código.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se marcó la cuenta como eliminada.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deletion_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se solicitó la eliminación.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete: marca la cuenta como eliminada sin borrar los datos.'),
        ),
    ]
