# Generated by Django 5.2.13 on 2026-05-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverificationcode_purpose_userprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
