# Generated by Django 5.2.13 on 2026-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('password_hash', models.CharField(help_text='Contraseña hasheada con django.contrib.auth.hashers.make_password.', max_length=128)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Cuántas veces se intentó verificar (anti brute-force).')),
            ],
            options={
                'verbose_name': 'Registro pendiente',
                'verbose_name_plural': 'Registros pendientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
