# Generated by Django 5.2.13 on 2026-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 del país resuelto por geolocalización (vacío si no se pudo resolver).', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se completó el registro (al verificar el código).', null=True),
        ),
    ]
