# Generated by Django 5.2.13 on 2026-05-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_country_code_userprofile_registration_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Intentos consecutivos de password incorrecta. Se resetea al login exitoso.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permanent_lock_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se bloqueó permanentemente la cuenta por intentos fallidos.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permanent_lock_reason',
            field=models.TextField(blank=True, default='', help_text='Motivos que se muestran al usuario en la card de cuenta bloqueada.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_lock_triggered',
            field=models.BooleanField(default=False, help_text='True una vez que se disparó el temp lock. La siguiente falla = bloqueo permanente.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temp_locked_until',
            field=models.DateTimeField(blank=True, help_text='Si > now, la cuenta está bloqueada temporalmente.', null=True),
        ),
        migrations.CreateModel(
            name='AccountRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Explicación del usuario de por qué quiere recuperar la cuenta.')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Nota del admin al aprobar/rechazar (opcional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_account_recovery_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de recuperación de cuenta',
                'verbose_name_plural': 'Solicitudes de recuperación de cuenta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_ac_status_7da5c4_idx'), models.Index(fields=['user', '-created_at'], name='accounts_ac_user_id_768d59_idx')],
            },
        ),
    ]
