# Generated by Django 5.2.13 on 2026-05-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_ip',
        ),
    ]
