# Generated by Django 5.2.13 on 2026-06-04 06:32

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountrecoveryrequest',
            new_name='tbl_solicit_estado_7b2f93_idx',
            old_name='accounts_ac_status_7da5c4_idx',
        ),
        migrations.RenameIndex(
            model_name='accountrecoveryrequest',
            new_name='tbl_solicit_id_usua_0eb849_idx',
            old_name='accounts_ac_user_id_768d59_idx',
        ),
        migrations.AddField(
            model_name='accountrecoveryrequest',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='admin_note',
            field=models.TextField(blank=True, db_column='nota_admin', help_text='Nota del admin al aprobar/rechazar (opcional).'),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='id',
            field=models.AutoField(db_column='id_solicitud_recuperacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='reason',
            field=models.TextField(db_column='motivo', help_text='Explicación del usuario de por qué quiere recuperar la cuenta.'),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_column='resuelto_en', null=True),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_column='id_resuelto_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_account_recovery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_column='estado', default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountrecoveryrequest',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='account_recovery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(db_column='intentos', default=0, help_text='Cuántas veces se intentó verificar este código (anti brute-force).'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(db_column='codigo', db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(db_column='expira_en'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='id',
            field=models.AutoField(db_column='id_codigo_verificacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Verificación de registro'), ('delete_account', 'Confirmar eliminación de cuenta')], db_column='proposito', db_index=True, default='register', help_text='Para qué acción se usa este código.', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='token',
            field=models.CharField(db_column='token', db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, db_column='usado_en', null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(db_column='expira_en'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.AutoField(db_column='id_token_recuperacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_column='direccion_ip', null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_column='token', db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, db_column='usado_en', null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='attempts',
            field=models.PositiveSmallIntegerField(db_column='intentos', default=0, help_text='Cuántas veces se intentó verificar (anti brute-force).'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='code',
            field=models.CharField(db_column='codigo', db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(db_column='correo', db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='expires_at',
            field=models.DateTimeField(db_column='expira_en'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='first_name',
            field=models.CharField(db_column='nombre', max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='id',
            field=models.AutoField(db_column='id_registro_pendiente', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='password_hash',
            field=models.CharField(db_column='hash_contrasena', help_text='Contraseña hasheada con django.contrib.auth.hashers.make_password.', max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='token',
            field=models.CharField(db_column='token', db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='used_at',
            field=models.DateTimeField(blank=True, db_column='usado_en', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alias_quota_extra',
            field=models.IntegerField(db_column='cupo_alias_extra', default=0, help_text='Ajuste de cupo de alias (positivo o negativo).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alias_unlimited',
            field=models.BooleanField(db_column='alias_ilimitados', default=False, help_text='Concede al usuario alias ilimitados sin volverlo admin.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', help_text='Foto de perfil. Si está vacío se usa avatar por defecto (iniciales).', null=True, upload_to=apps.accounts.models._avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_session_key',
            field=models.CharField(blank=True, db_column='sesion_actual', default='', help_text='Session key activa. Cualquier otra sesión del usuario será cerrada.', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='eliminado_en', help_text='Cuándo se marcó la cuenta como eliminada.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deletion_ip',
            field=models.GenericIPAddressField(blank=True, db_column='ip_eliminacion', help_text='IP desde donde se solicitó la eliminación.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(db_column='correo_verificado', default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(db_column='intentos_fallidos', default=0, help_text='Intentos consecutivos de password incorrecta. Se resetea al login exitoso.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='forward_safe_emails',
            field=models.BooleanField(db_column='reenviar_correos_seguros', default=False, help_text='Reenviar correos seguros al correo real del usuario.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(db_column='id_perfil_usuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(db_column='eliminado', default=False, help_text='Soft delete: marca la cuenta como eliminada sin borrar los datos.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_toast_notif_id',
            field=models.PositiveBigIntegerField(db_column='ultimo_toast_id', default=0, help_text='ID máximo de notificación cuyo toast ya se mostró.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permanent_lock_at',
            field=models.DateTimeField(blank=True, db_column='bloqueo_perm_en', help_text='Cuándo se bloqueó permanentemente la cuenta por intentos fallidos.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permanent_lock_reason',
            field=models.TextField(blank=True, db_column='motivo_bloqueo_perm', default='', help_text='Motivos que se muestran al usuario en la card de cuenta bloqueada.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session_last_activity',
            field=models.DateTimeField(blank=True, db_column='ultima_actividad_sesion', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temp_lock_triggered',
            field=models.BooleanField(db_column='bloqueo_temp_activado', default=False, help_text='True una vez que se disparó el temp lock. La siguiente falla = bloqueo permanente.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temp_locked_until',
            field=models.DateTimeField(blank=True, db_column='bloqueo_temp_hasta', help_text='Si > now, la cuenta está bloqueada temporalmente.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='actualizado_en'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='accountrecoveryrequest',
            table='tbl_solicitud_recuperacion',
        ),
        migrations.AlterModelTable(
            name='emailverificationcode',
            table='tbl_codigo_verificacion',
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='tbl_token_recuperacion',
        ),
        migrations.AlterModelTable(
            name='pendingregistration',
            table='tbl_registro_pendiente',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='tbl_perfil_usuario',
        ),
    ]
