# Generated by Django 5.2.13 on 2026-06-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_accounts_ac_status_7da5c4_idx_tbl_solicit_estado_7b2f93_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_session_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='permanent_lock_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='permanent_lock_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='session_last_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_lock_triggered',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_locked_until',
        ),
        migrations.CreateModel(
            name='AccountLock',
            fields=[
                ('id', models.AutoField(db_column='id_bloqueo_cuenta', primary_key=True, serialize=False)),
                ('failed_login_attempts', models.PositiveIntegerField(db_column='intentos_fallidos', default=0, help_text='Intentos consecutivos de password incorrecta. Se resetea al login exitoso.')),
                ('temp_locked_until', models.DateTimeField(blank=True, db_column='bloqueo_temp_hasta', help_text='Si > now, la cuenta está bloqueada temporalmente.', null=True)),
                ('temp_lock_triggered', models.BooleanField(db_column='bloqueo_temp_activado', default=False, help_text='True una vez que se disparó el temp lock. La siguiente falla = bloqueo permanente.')),
                ('permanent_lock_reason', models.TextField(blank=True, db_column='motivo_bloqueo_perm', default='', help_text='Motivos que se muestran al usuario en la card de cuenta bloqueada.')),
                ('permanent_lock_at', models.DateTimeField(blank=True, db_column='bloqueo_perm_en', help_text='Cuándo se bloqueó permanentemente la cuenta por intentos fallidos.', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('profile', models.OneToOneField(db_column='id_perfil_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_bloqueo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(db_column='id_sesion_usuario', primary_key=True, serialize=False)),
                ('current_session_key', models.CharField(blank=True, db_column='sesion_actual', default='', help_text='Session key activa. Cualquier otra sesión del usuario será cerrada.', max_length=40)),
                ('session_last_activity', models.DateTimeField(blank=True, db_column='ultima_actividad_sesion', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('profile', models.OneToOneField(db_column='id_perfil_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='session', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'tbl_sesion_usuario',
            },
        ),
    ]
