
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        libmagic1 \
        file \
        p7zip-full \
        unrar-free \
        unzip \
        binutils \
        strace \
        procps \
        coreutils \
    && rm -rf /var/lib/apt/lists/*



RUN pip install --no-cache-dir \
        --timeout=120 \
        --retries=10 \
        python-magic==0.4.27 \
        yara-python==4.5.1 \
        oletools==0.60.2 \
        pefile==2024.8.26 \
        olefile==0.47 \
        rarfile==4.2 \
        py7zr==0.21.1 \
        tldextract==5.1.3


COPY apps/sandbox/ /app/sandbox/


RUN useradd -m -u 1000 -s /bin/bash sandbox \
    && chown -R sandbox:sandbox /app
USER sandbox


CMD ["python", "/app/sandbox/run_analysis.py"]
