version: '3.9'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=email_seguro.settings
    depends_on:
      - sandbox
    networks:
      - web_net

  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    volumes:
      - media_data:/app/media   
    environment:
      - SANDBOX_MODE=1
    
    networks:
      - sandbox_net             

volumes:
  media_data:

networks:
  web_net:
    driver: bridge
  sandbox_net:
    driver: bridge
    internal: true              