-- ============================================================
-- migrar_normalizacion.sql
-- Crea nuevas tablas normalizadas, migra datos existentes
-- y elimina columnas antiguas de tablas padre.
-- ============================================================
BEGIN;

-- ==================== tbl_sesion_usuario ====================
CREATE TABLE tbl_sesion_usuario (
    id_sesion_usuario    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_actual        VARCHAR(40) NOT NULL DEFAULT '',
    ultima_actividad_sesion TIMESTAMPTZ,
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    id_perfil_usuario    BIGINT NOT NULL UNIQUE
        REFERENCES tbl_perfil_usuario(id_perfil_usuario) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_sesion_usuario (id_perfil_usuario, sesion_actual, ultima_actividad_sesion, activo)
SELECT id_perfil_usuario, sesion_actual, ultima_actividad_sesion, TRUE
FROM tbl_perfil_usuario;

ALTER TABLE tbl_perfil_usuario DROP COLUMN sesion_actual;
ALTER TABLE tbl_perfil_usuario DROP COLUMN ultima_actividad_sesion;

-- ==================== tbl_bloqueo_cuenta ====================
CREATE TABLE tbl_bloqueo_cuenta (
    id_bloqueo_cuenta    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intentos_fallidos    INTEGER NOT NULL DEFAULT 0 CHECK (intentos_fallidos >= 0),
    bloqueo_temp_hasta   TIMESTAMPTZ,
    bloqueo_temp_activado BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_bloqueo_perm  TEXT NOT NULL DEFAULT '',
    bloqueo_perm_en      TIMESTAMPTZ,
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    id_perfil_usuario    BIGINT NOT NULL UNIQUE
        REFERENCES tbl_perfil_usuario(id_perfil_usuario) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_bloqueo_cuenta (id_perfil_usuario, intentos_fallidos, bloqueo_temp_hasta, bloqueo_temp_activado, motivo_bloqueo_perm, bloqueo_perm_en, activo)
SELECT id_perfil_usuario, intentos_fallidos, bloqueo_temp_hasta, bloqueo_temp_activado, motivo_bloqueo_perm, bloqueo_perm_en, TRUE
FROM tbl_perfil_usuario;

ALTER TABLE tbl_perfil_usuario DROP COLUMN intentos_fallidos;
ALTER TABLE tbl_perfil_usuario DROP COLUMN bloqueo_temp_hasta;
ALTER TABLE tbl_perfil_usuario DROP COLUMN bloqueo_temp_activado;
ALTER TABLE tbl_perfil_usuario DROP COLUMN motivo_bloqueo_perm;
ALTER TABLE tbl_perfil_usuario DROP COLUMN bloqueo_perm_en;

-- ==================== tbl_verificacion_correo ====================
CREATE TABLE tbl_verificacion_correo (
    id_verificacion_correo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veredicto_auth       VARCHAR(12) NOT NULL DEFAULT 'unverified',
    auth_spf             VARCHAR(10) NOT NULL DEFAULT '',
    auth_dkim            VARCHAR(10) NOT NULL DEFAULT '',
    auth_dmarc           VARCHAR(10) NOT NULL DEFAULT '',
    firmado_por          VARCHAR(120) NOT NULL DEFAULT '',
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    id_mensaje_correo    BIGINT NOT NULL UNIQUE
        REFERENCES tbl_mensaje_correo(id_mensaje_correo) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_verificacion_correo (id_mensaje_correo, veredicto_auth, auth_spf, auth_dkim, auth_dmarc, firmado_por, activo)
SELECT id_mensaje_correo, veredicto_auth, auth_spf, auth_dkim, auth_dmarc, firmado_por, TRUE
FROM tbl_mensaje_correo;

ALTER TABLE tbl_mensaje_correo DROP COLUMN veredicto_auth;
ALTER TABLE tbl_mensaje_correo DROP COLUMN auth_spf;
ALTER TABLE tbl_mensaje_correo DROP COLUMN auth_dkim;
ALTER TABLE tbl_mensaje_correo DROP COLUMN auth_dmarc;
ALTER TABLE tbl_mensaje_correo DROP COLUMN firmado_por;

-- ==================== tbl_adjunto_correo ====================
CREATE TABLE tbl_adjunto_correo (
    id_adjunto_correo    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tiene_adjunto        BOOLEAN NOT NULL DEFAULT FALSE,
    nombre_adjunto       VARCHAR(255) NOT NULL DEFAULT '',
    ruta_adjunto         VARCHAR(500) NOT NULL DEFAULT '',
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    id_mensaje_correo    BIGINT NOT NULL UNIQUE
        REFERENCES tbl_mensaje_correo(id_mensaje_correo) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_adjunto_correo (id_mensaje_correo, tiene_adjunto, nombre_adjunto, ruta_adjunto, activo)
SELECT id_mensaje_correo, tiene_adjunto, nombre_adjunto, ruta_adjunto, TRUE
FROM tbl_mensaje_correo;

ALTER TABLE tbl_mensaje_correo DROP COLUMN tiene_adjunto;
ALTER TABLE tbl_mensaje_correo DROP COLUMN nombre_adjunto;
ALTER TABLE tbl_mensaje_correo DROP COLUMN ruta_adjunto;

-- ==================== tbl_info_archivo ====================
CREATE TABLE tbl_info_archivo (
    id_info_archivo       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo        VARCHAR(255) NOT NULL DEFAULT '',
    tipo_mime_real        VARCHAR(100) NOT NULL DEFAULT '',
    hash_sha256           VARCHAR(64) NOT NULL DEFAULT '',
    hash_md5              VARCHAR(32) NOT NULL DEFAULT '',
    tamano_archivo        BIGINT NOT NULL DEFAULT 0,
    extension             VARCHAR(20) NOT NULL DEFAULT '',
    extension_falsificada BOOLEAN NOT NULL DEFAULT FALSE,
    activo                BOOLEAN NOT NULL DEFAULT TRUE,
    id_analisis_sandbox   BIGINT NOT NULL UNIQUE
        REFERENCES tbl_analisis_sandbox(id_analisis_sandbox) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_info_archivo (id_analisis_sandbox, nombre_archivo, tipo_mime_real, hash_sha256, hash_md5, tamano_archivo, extension, extension_falsificada, activo)
SELECT id_analisis_sandbox, nombre_archivo, tipo_mime_real, hash_sha256, hash_md5, tamano_archivo, extension, extension_falsificada, TRUE
FROM tbl_analisis_sandbox;

ALTER TABLE tbl_analisis_sandbox DROP COLUMN nombre_archivo;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN tipo_mime_real;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN hash_sha256;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN hash_md5;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN tamano_archivo;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN extension;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN extension_falsificada;

-- ==================== tbl_analisis_dinamico ====================
CREATE TABLE tbl_analisis_dinamico (
    id_analisis_dinamico   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria              VARCHAR(20) NOT NULL DEFAULT 'unknown',
    coincidencias_yara     JSONB NOT NULL DEFAULT '[]',
    conexiones_red         JSONB NOT NULL DEFAULT '[]',
    procesos_hijos         JSONB NOT NULL DEFAULT '[]',
    archivos_escritos      JSONB NOT NULL DEFAULT '[]',
    evidencia              JSONB NOT NULL DEFAULT '[]',
    iocs                   JSONB NOT NULL DEFAULT '{}',
    analizadores_ejecutados JSONB NOT NULL DEFAULT '[]',
    activo                 BOOLEAN NOT NULL DEFAULT TRUE,
    id_analisis_sandbox    BIGINT NOT NULL UNIQUE
        REFERENCES tbl_analisis_sandbox(id_analisis_sandbox) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_analisis_dinamico (id_analisis_sandbox, categoria, coincidencias_yara, conexiones_red, procesos_hijos, archivos_escritos, evidencia, iocs, analizadores_ejecutados, activo)
SELECT id_analisis_sandbox, categoria, coincidencias_yara, conexiones_red, procesos_hijos, archivos_escritos, evidencia, iocs, analizadores_ejecutados, TRUE
FROM tbl_analisis_sandbox;

ALTER TABLE tbl_analisis_sandbox DROP COLUMN categoria;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN coincidencias_yara;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN conexiones_red;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN procesos_hijos;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN archivos_escritos;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN evidencia;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN iocs;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN analizadores_ejecutados;

-- ==================== tbl_analisis_cuerpo ====================
CREATE TABLE tbl_analisis_cuerpo (
    id_analisis_cuerpo   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puntaje_cuerpo       INTEGER NOT NULL DEFAULT 0,
    evidencia_cuerpo     JSONB NOT NULL DEFAULT '[]',
    amenaza_cuerpo       VARCHAR(200) NOT NULL DEFAULT '',
    reportes_adjuntos    JSONB NOT NULL DEFAULT '[]',
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    id_analisis_sandbox  BIGINT NOT NULL UNIQUE
        REFERENCES tbl_analisis_sandbox(id_analisis_sandbox) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_analisis_cuerpo (id_analisis_sandbox, puntaje_cuerpo, evidencia_cuerpo, amenaza_cuerpo, reportes_adjuntos, activo)
SELECT id_analisis_sandbox, puntaje_cuerpo, evidencia_cuerpo, amenaza_cuerpo, reportes_adjuntos, TRUE
FROM tbl_analisis_sandbox;

ALTER TABLE tbl_analisis_sandbox DROP COLUMN puntaje_cuerpo;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN evidencia_cuerpo;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN amenaza_cuerpo;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN reportes_adjuntos;

-- ==================== tbl_resultado_ia ====================
CREATE TABLE tbl_resultado_ia (
    id_resultado_ia      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veredicto_ia         VARCHAR(20) NOT NULL DEFAULT '',
    tipo_amenaza_ia      VARCHAR(100) NOT NULL DEFAULT '',
    explicacion_ia       TEXT NOT NULL DEFAULT '',
    recomendacion_ia     TEXT NOT NULL DEFAULT '',
    generado_ia_en       TIMESTAMPTZ,
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    id_analisis_sandbox  BIGINT NOT NULL UNIQUE
        REFERENCES tbl_analisis_sandbox(id_analisis_sandbox) DEFERRABLE INITIALLY DEFERRED
);

INSERT INTO tbl_resultado_ia (id_analisis_sandbox, veredicto_ia, tipo_amenaza_ia, explicacion_ia, recomendacion_ia, generado_ia_en, activo)
SELECT id_analisis_sandbox, veredicto_ia, tipo_amenaza_ia, explicacion_ia, recomendacion_ia, generado_ia_en, TRUE
FROM tbl_analisis_sandbox;

ALTER TABLE tbl_analisis_sandbox DROP COLUMN veredicto_ia;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN tipo_amenaza_ia;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN explicacion_ia;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN recomendacion_ia;
ALTER TABLE tbl_analisis_sandbox DROP COLUMN generado_ia_en;

COMMIT;
