# Generated by Django 5.2.13 on 2026-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sandbox_multi_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='attachments_reports',
            field=models.JSONField(blank=True, default=list, help_text='Lista de reportes por cada adjunto [{filename, size, mime, sha256, score,  level, threat, evidence[], iocs{}}, ...]'),
        ),
    ]
