# Generated by Django 5.2.13 on 2026-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, help_text='Cuerpo HTML del correo (se renderiza en iframe sandbox)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True, help_text='Cuerpo en texto plano (para preview y análisis)'),
        ),
    ]
