# Generated by Django 5.2.13 on 2026-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_emailmessage_body_html_alter_emailmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forward_safe_emails',
            field=models.BooleanField(default=False, help_text='Reenviar correos seguros al correo real del usuario.'),
        ),
    ]
