# Generated by Django 5.2.13 on 2026-04-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('real_mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('extension_spoof', models.BooleanField(default=False, help_text='La extensión no coincide con el MIME real')),
                ('yara_matches', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('executable', 'Ejecutable'), ('office', 'Documento Office'), ('pdf', 'PDF'), ('archive', 'Archivo comprimido'), ('script', 'Script'), ('body', 'Cuerpo del correo'), ('url', 'URL'), ('aggregate', 'Agregado'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('network_connections', models.JSONField(blank=True, default=list)),
                ('child_processes', models.JSONField(blank=True, default=list)),
                ('file_writes', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Lista de indicadores con type, detail y severity')),
                ('iocs', models.JSONField(blank=True, default=dict, help_text='URLs, IPs, dominios y hashes detectados')),
                ('analyzers_run', models.JSONField(blank=True, default=list, help_text='Analizadores que se ejecutaron')),
                ('body_score', models.IntegerField(default=0, help_text='Puntuación del análisis del cuerpo del correo')),
                ('body_evidence', models.JSONField(blank=True, default=list, help_text='Evidencia del análisis del cuerpo')),
                ('body_threat', models.CharField(blank=True, max_length=200)),
                ('attachments_reports', models.JSONField(blank=True, default=list, help_text='Lista de reportes por cada adjunto [{filename, size, mime, sha256, score,  level, threat, evidence[], iocs{}}, ...]')),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('safe', 'Seguro (0–30)'), ('warning', 'Sospechoso (31–60)'), ('danger', 'Alto riesgo (61–80)'), ('malware', 'Malware (81–100)')], default='safe', max_length=10)),
                ('threat_name', models.CharField(blank=True, max_length=200)),
                ('blocked', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='mail.emailmessage')),
            ],
            options={
                'verbose_name': 'Análisis sandbox',
                'verbose_name_plural': 'Análisis sandbox',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
