# Generated by Django 5.2.13 on 2026-06-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxAnalysis',
            fields=[
                ('id', models.AutoField(db_column='id_analisis_sandbox', primary_key=True, serialize=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_column='analizado_en')),
                ('risk_score', models.IntegerField(db_column='puntaje_riesgo', default=0)),
                ('risk_level', models.CharField(choices=[('safe', 'Seguro (0-30)'), ('warning', 'Sospechoso (31-60)'), ('danger', 'Alto riesgo (61-80)'), ('malware', 'Malware (81-100)')], db_column='nivel_riesgo', default='safe', max_length=10)),
                ('threat_name', models.CharField(blank=True, db_column='nombre_amenaza', max_length=200)),
                ('blocked', models.BooleanField(db_column='bloqueado', default=False)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('email', models.OneToOneField(db_column='id_correo', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='mail.emailmessage')),
            ],
            options={
                'verbose_name': 'Análisis sandbox',
                'verbose_name_plural': 'Análisis sandbox',
                'db_table': 'tbl_analisis_sandbox',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='IAResult',
            fields=[
                ('id', models.AutoField(db_column='id_resultado_ia', primary_key=True, serialize=False)),
                ('ai_verdict', models.CharField(blank=True, db_column='veredicto_ia', help_text='MALICIOSO / SOSPECHOSO / SEGURO', max_length=20)),
                ('ai_threat_type', models.CharField(blank=True, db_column='tipo_amenaza_ia', help_text='Tipo de amenaza (Phishing, Malware, etc.)', max_length=100)),
                ('ai_explanation', models.TextField(blank=True, db_column='explicacion_ia', help_text='Respuesta de la IA en Markdown (EXPLICACION)')),
                ('ai_recommendation', models.TextField(blank=True, db_column='recomendacion_ia', help_text='Respuesta de la IA en Markdown (RECOMENDACION)')),
                ('ai_generated_at', models.DateTimeField(blank=True, db_column='generado_ia_en', help_text='Cuándo se generó el análisis IA por última vez', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('analysis', models.OneToOneField(db_column='id_analisis_sandbox', on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='sandbox.sandboxanalysis')),
            ],
            options={
                'db_table': 'tbl_resultado_ia',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(db_column='id_info_archivo', primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='nombre_archivo', max_length=255)),
                ('real_mime_type', models.CharField(blank=True, db_column='tipo_mime_real', max_length=100)),
                ('sha256_hash', models.CharField(blank=True, db_column='hash_sha256', max_length=64)),
                ('md5_hash', models.CharField(blank=True, db_column='hash_md5', max_length=32)),
                ('file_size', models.BigIntegerField(db_column='tamano_archivo', default=0)),
                ('extension', models.CharField(blank=True, db_column='extension', max_length=20)),
                ('extension_spoof', models.BooleanField(db_column='extension_falsificada', default=False, help_text='La extensión no coincide con el MIME real')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('analysis', models.OneToOneField(db_column='id_analisis_sandbox', on_delete=django.db.models.deletion.CASCADE, related_name='file_info', to='sandbox.sandboxanalysis')),
            ],
            options={
                'db_table': 'tbl_info_archivo',
            },
        ),
        migrations.CreateModel(
            name='DynamicAnalysis',
            fields=[
                ('id', models.AutoField(db_column='id_analisis_dinamico', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('executable', 'Ejecutable'), ('office', 'Documento Office'), ('pdf', 'PDF'), ('archive', 'Archivo comprimido'), ('script', 'Script'), ('body', 'Cuerpo del correo'), ('url', 'URL'), ('aggregate', 'Agregado'), ('unknown', 'Desconocido')], db_column='categoria', default='unknown', max_length=20)),
                ('yara_matches', models.JSONField(blank=True, db_column='coincidencias_yara', default=list)),
                ('network_connections', models.JSONField(blank=True, db_column='conexiones_red', default=list)),
                ('child_processes', models.JSONField(blank=True, db_column='procesos_hijos', default=list)),
                ('file_writes', models.JSONField(blank=True, db_column='archivos_escritos', default=list)),
                ('evidence', models.JSONField(blank=True, db_column='evidencia', default=list, help_text='Lista de indicadores con type, detail y severity')),
                ('iocs', models.JSONField(blank=True, db_column='iocs', default=dict, help_text='URLs, IPs, dominios y hashes detectados')),
                ('analyzers_run', models.JSONField(blank=True, db_column='analizadores_ejecutados', default=list, help_text='Analizadores que se ejecutaron')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('analysis', models.OneToOneField(db_column='id_analisis_sandbox', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='sandbox.sandboxanalysis')),
            ],
            options={
                'db_table': 'tbl_analisis_dinamico',
            },
        ),
        migrations.CreateModel(
            name='BodyAnalysis',
            fields=[
                ('id', models.AutoField(db_column='id_analisis_cuerpo', primary_key=True, serialize=False)),
                ('body_score', models.IntegerField(db_column='puntaje_cuerpo', default=0, help_text='Puntuación del análisis del cuerpo del correo')),
                ('body_evidence', models.JSONField(blank=True, db_column='evidencia_cuerpo', default=list, help_text='Evidencia del análisis del cuerpo')),
                ('body_threat', models.CharField(blank=True, db_column='amenaza_cuerpo', max_length=200)),
                ('attachments_reports', models.JSONField(blank=True, db_column='reportes_adjuntos', default=list, help_text='Lista de reportes por cada adjunto')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('analysis', models.OneToOneField(db_column='id_analisis_sandbox', on_delete=django.db.models.deletion.CASCADE, related_name='body_analysis', to='sandbox.sandboxanalysis')),
            ],
            options={
                'db_table': 'tbl_analisis_cuerpo',
            },
        ),
    ]
