# Generated by Django 5.2.13 on 2026-05-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='SHA-1 de "type|detail" normalizado', max_length=64, unique=True)),
                ('evidence_type', models.CharField(help_text='Tipo de evidencia o regla YARA original', max_length=120)),
                ('evidence_detail', models.TextField(blank=True, help_text='Texto detail del análisis (contexto)')),
                ('explanation', models.TextField(help_text='Respuesta generada por la IA')),
                ('model_used', models.CharField(blank=True, help_text='Modelo Groq usado (para auditoría)', max_length=80)),
                ('hit_count', models.PositiveIntegerField(default=1, help_text='Cuántas veces se reusó este cache')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Explicación cacheada',
                'verbose_name_plural': 'Explicaciones cacheadas',
                'ordering': ['-last_used_at'],
            },
        ),
    ]
