# Generated by Django 5.2.13 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyanalysis',
            name='attachments_reports',
            field=models.JSONField(blank=True, db_column='anc_reportes_adjuntos', default=list, help_text='Lista de reportes por cada adjunto'),
        ),
        migrations.AlterField(
            model_name='bodyanalysis',
            name='body_evidence',
            field=models.JSONField(blank=True, db_column='anc_evidencia_cuerpo', default=list, help_text='Evidencia del análisis del cuerpo'),
        ),
        migrations.AlterField(
            model_name='bodyanalysis',
            name='body_score',
            field=models.IntegerField(db_column='anc_puntaje_cuerpo', default=0, help_text='Puntuación del análisis del cuerpo del correo'),
        ),
        migrations.AlterField(
            model_name='bodyanalysis',
            name='body_threat',
            field=models.CharField(blank=True, db_column='anc_amenaza_cuerpo', max_length=200),
        ),
        migrations.AlterField(
            model_name='bodyanalysis',
            name='is_active',
            field=models.BooleanField(db_column='anc_activo', default=True),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='analyzers_run',
            field=models.JSONField(blank=True, db_column='and_analizadores_ejecutados', default=list, help_text='Analizadores que se ejecutaron'),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='category',
            field=models.CharField(choices=[('executable', 'Ejecutable'), ('office', 'Documento Office'), ('pdf', 'PDF'), ('archive', 'Archivo comprimido'), ('script', 'Script'), ('body', 'Cuerpo del correo'), ('url', 'URL'), ('aggregate', 'Agregado'), ('unknown', 'Desconocido')], db_column='and_categoria', default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='child_processes',
            field=models.JSONField(blank=True, db_column='and_procesos_hijos', default=list),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='evidence',
            field=models.JSONField(blank=True, db_column='and_evidencia', default=list, help_text='Lista de indicadores con type, detail y severity'),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='file_writes',
            field=models.JSONField(blank=True, db_column='and_archivos_escritos', default=list),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='iocs',
            field=models.JSONField(blank=True, db_column='and_iocs', default=dict, help_text='URLs, IPs, dominios y hashes detectados'),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='is_active',
            field=models.BooleanField(db_column='and_activo', default=True),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='network_connections',
            field=models.JSONField(blank=True, db_column='and_conexiones_red', default=list),
        ),
        migrations.AlterField(
            model_name='dynamicanalysis',
            name='yara_matches',
            field=models.JSONField(blank=True, db_column='and_coincidencias_yara', default=list),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='extension',
            field=models.CharField(blank=True, db_column='ifa_extension', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='extension_spoof',
            field=models.BooleanField(db_column='ifa_extension_falsificada', default=False, help_text='La extensión no coincide con el MIME real'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_size',
            field=models.BigIntegerField(db_column='ifa_tamano_archivo', default=0),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='filename',
            field=models.CharField(db_column='ifa_nombre_archivo', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='is_active',
            field=models.BooleanField(db_column='ifa_activo', default=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='md5_hash',
            field=models.CharField(blank=True, db_column='ifa_hash_md5', max_length=32),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='real_mime_type',
            field=models.CharField(blank=True, db_column='ifa_tipo_mime_real', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='sha256_hash',
            field=models.CharField(blank=True, db_column='ifa_hash_sha256', max_length=64),
        ),
        migrations.AlterField(
            model_name='iaresult',
            name='ai_explanation',
            field=models.TextField(blank=True, db_column='ria_explicacion_ia', help_text='Respuesta de la IA en Markdown (EXPLICACION)'),
        ),
        migrations.AlterField(
            model_name='iaresult',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, db_column='ria_generado_ia_en', help_text='Cuándo se generó el análisis IA por última vez', null=True),
        ),
        migrations.AlterField(
            model_name='iaresult',
            name='ai_recommendation',
            field=models.TextField(blank=True, db_column='ria_recomendacion_ia', help_text='Respuesta de la IA en Markdown (RECOMENDACION)'),
        ),
        migrations.AlterField(
            model_name='iaresult',
            name='ai_threat_type',
            field=models.CharField(blank=True, db_column='ria_tipo_amenaza_ia', help_text='Tipo de amenaza (Phishing, Malware, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='iaresult',
            name='ai_verdict',
            field=models.CharField(blank=True, db_column='ria_veredicto_ia', help_text='MALICIOSO / SOSPECHOSO / SEGURO', max_length=20),
        ),
        migrations.AlterField(
            model_name='iaresult',
            name='is_active',
            field=models.BooleanField(db_column='ria_activo', default=True),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ans_analizado_en'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='blocked',
            field=models.BooleanField(db_column='ans_bloqueado', default=False),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='is_active',
            field=models.BooleanField(db_column='ans_activo', default=True),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='risk_level',
            field=models.CharField(choices=[('safe', 'Seguro (0-30)'), ('warning', 'Sospechoso (31-60)'), ('danger', 'Alto riesgo (61-80)'), ('malware', 'Malware (81-100)')], db_column='ans_nivel_riesgo', default='safe', max_length=10),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='risk_score',
            field=models.IntegerField(db_column='ans_puntaje_riesgo', default=0),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='threat_name',
            field=models.CharField(blank=True, db_column='ans_nombre_amenaza', max_length=200),
        ),
    ]
