# Generated by Django 5.2.7 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_alter_bodyanalysis_attachments_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='risk_score',
            field=models.IntegerField(db_column='ans_puntaje_riesgo', db_index=True, default=0),
        ),
    ]
