# Generated by Django 5.2.13 on 2026-05-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_termexplanation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermExplanation',
        ),
    ]
