# Generated by Django 5.2.13 on 2026-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_delete_termexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxanalysis',
            name='ai_explanation',
            field=models.TextField(blank=True, help_text='Respuesta de la IA en Markdown (EXPLICACION)'),
        ),
        migrations.AddField(
            model_name='sandboxanalysis',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se generó el análisis IA por última vez', null=True),
        ),
        migrations.AddField(
            model_name='sandboxanalysis',
            name='ai_recommendation',
            field=models.TextField(blank=True, help_text='Respuesta de la IA en Markdown (RECOMENDACION)'),
        ),
        migrations.AddField(
            model_name='sandboxanalysis',
            name='ai_threat_type',
            field=models.CharField(blank=True, help_text='Tipo de amenaza (Phishing, Malware, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='sandboxanalysis',
            name='ai_verdict',
            field=models.CharField(blank=True, help_text='MALICIOSO / SOSPECHOSO / SEGURO', max_length=20),
        ),
    ]
