# Generated by Django 5.2.7 on 2026-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_draft_mail_draft_user_deleted_idx_and_more'),
        ('sandbox', '0003_add_perf_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sandboxanalysis',
            index=models.Index(fields=['-analyzed_at'], name='sandbox_analyzed_at_idx'),
        ),
    ]
