# Generated by Django 5.2.13 on 2026-06-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_draft_is_active_emailmessage_is_active_and_more'),
        ('sandbox', '0004_sandboxanalysis_ai_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxanalysis',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='ai_explanation',
            field=models.TextField(blank=True, db_column='explicacion_ia', help_text='Respuesta de la IA en Markdown (EXPLICACION)'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, db_column='generado_ia_en', help_text='Cuándo se generó el análisis IA por última vez', null=True),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='ai_recommendation',
            field=models.TextField(blank=True, db_column='recomendacion_ia', help_text='Respuesta de la IA en Markdown (RECOMENDACION)'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='ai_threat_type',
            field=models.CharField(blank=True, db_column='tipo_amenaza_ia', help_text='Tipo de amenaza (Phishing, Malware, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='ai_verdict',
            field=models.CharField(blank=True, db_column='veredicto_ia', help_text='MALICIOSO / SOSPECHOSO / SEGURO', max_length=20),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now_add=True, db_column='analizado_en'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='analyzers_run',
            field=models.JSONField(blank=True, db_column='analizadores_ejecutados', default=list, help_text='Analizadores que se ejecutaron'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='attachments_reports',
            field=models.JSONField(blank=True, db_column='reportes_adjuntos', default=list, help_text='Lista de reportes por cada adjunto'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='blocked',
            field=models.BooleanField(db_column='bloqueado', default=False),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='body_evidence',
            field=models.JSONField(blank=True, db_column='evidencia_cuerpo', default=list, help_text='Evidencia del análisis del cuerpo'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='body_score',
            field=models.IntegerField(db_column='puntaje_cuerpo', default=0, help_text='Puntuación del análisis del cuerpo del correo'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='body_threat',
            field=models.CharField(blank=True, db_column='amenaza_cuerpo', max_length=200),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='category',
            field=models.CharField(choices=[('executable', 'Ejecutable'), ('office', 'Documento Office'), ('pdf', 'PDF'), ('archive', 'Archivo comprimido'), ('script', 'Script'), ('body', 'Cuerpo del correo'), ('url', 'URL'), ('aggregate', 'Agregado'), ('unknown', 'Desconocido')], db_column='categoria', default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='child_processes',
            field=models.JSONField(blank=True, db_column='procesos_hijos', default=list),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='email',
            field=models.OneToOneField(db_column='id_correo', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='mail.emailmessage'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='evidence',
            field=models.JSONField(blank=True, db_column='evidencia', default=list, help_text='Lista de indicadores con type, detail y severity'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='extension',
            field=models.CharField(blank=True, db_column='extension', max_length=20),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='extension_spoof',
            field=models.BooleanField(db_column='extension_falsificada', default=False, help_text='La extensión no coincide con el MIME real'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='file_size',
            field=models.BigIntegerField(db_column='tamano_archivo', default=0),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='file_writes',
            field=models.JSONField(blank=True, db_column='archivos_escritos', default=list),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='filename',
            field=models.CharField(db_column='nombre_archivo', max_length=255),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='id',
            field=models.AutoField(db_column='id_analisis_sandbox', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='iocs',
            field=models.JSONField(blank=True, db_column='iocs', default=dict, help_text='URLs, IPs, dominios y hashes detectados'),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='md5_hash',
            field=models.CharField(blank=True, db_column='hash_md5', max_length=32),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='network_connections',
            field=models.JSONField(blank=True, db_column='conexiones_red', default=list),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='real_mime_type',
            field=models.CharField(blank=True, db_column='tipo_mime_real', max_length=100),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='risk_level',
            field=models.CharField(choices=[('safe', 'Seguro (0–30)'), ('warning', 'Sospechoso (31–60)'), ('danger', 'Alto riesgo (61–80)'), ('malware', 'Malware (81–100)')], db_column='nivel_riesgo', default='safe', max_length=10),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='risk_score',
            field=models.IntegerField(db_column='puntaje_riesgo', default=0),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='sha256_hash',
            field=models.CharField(blank=True, db_column='hash_sha256', max_length=64),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='threat_name',
            field=models.CharField(blank=True, db_column='nombre_amenaza', max_length=200),
        ),
        migrations.AlterField(
            model_name='sandboxanalysis',
            name='yara_matches',
            field=models.JSONField(blank=True, db_column='coincidencias_yara', default=list),
        ),
        migrations.AlterModelTable(
            name='sandboxanalysis',
            table='tbl_analisis_sandbox',
        ),
    ]
