# Generated by Django 6.0.4 on 2026-04-17 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Etiqueta: ej. Amazon, Foro Reddit', max_length=100)),
                ('address', models.EmailField(help_text='Dirección generada: amazon_x7k2@securemail.app', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Alias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100. 0=seguro, 100=malware')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app.alias')),
            ],
            options={
                'verbose_name': 'Correo recibido',
                'verbose_name_plural': 'Correos recibidos',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SandboxAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('real_mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('yara_matches', models.JSONField(blank=True, default=list)),
                ('network_connections', models.JSONField(blank=True, default=list)),
                ('child_processes', models.JSONField(blank=True, default=list)),
                ('file_writes', models.JSONField(blank=True, default=list)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('safe', 'Seguro (0–30)'), ('warning', 'Sospechoso (31–60)'), ('danger', 'Alto riesgo (61–80)'), ('malware', 'Malware (81–100)')], default='safe', max_length=10)),
                ('threat_name', models.CharField(blank=True, max_length=200)),
                ('blocked', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='app.emailmessage')),
            ],
            options={
                'verbose_name': 'Análisis sandbox',
                'verbose_name_plural': 'Análisis sandbox',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
