# Generated by Django 5.2.13 on 2026-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='body_html_raw',
            field=models.TextField(blank=True, help_text='HTML ORIGINAL sin neutralizar (se usa al reenviar al correo real)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, help_text='HTML neutralizado (links/imágenes bloqueados — se muestra en la bandeja)'),
        ),
    ]
