# Generated by Django 5.2.13 on 2026-04-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_emailmessage_body_html_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_session_key',
            field=models.CharField(blank=True, default='', help_text='Session key activa. Cualquier otra sesión del usuario será cerrada.', max_length=40),
        ),
    ]
