# Generated by Django 5.2.13 on 2026-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile_current_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
