# Generated by Django 5.2.13 on 2026-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userprofile_email_verified_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='auth_dkim',
            field=models.CharField(blank=True, help_text='pass / fail / none', max_length=10),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='auth_dmarc',
            field=models.CharField(blank=True, help_text='pass / fail / none', max_length=10),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='auth_signed_by',
            field=models.CharField(blank=True, help_text='Dominio que firmó con DKIM (header.d=)', max_length=120),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='auth_spf',
            field=models.CharField(blank=True, help_text='pass / fail / softfail / neutral / none', max_length=10),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='auth_verdict',
            field=models.CharField(blank=True, choices=[('verified', 'Verificado criptográficamente'), ('unverified', 'Sin verificar'), ('spoofed', 'Suplantación detectada')], default='unverified', max_length=12),
        ),
        migrations.AlterField(
            model_name='alias',
            name='address',
            field=models.EmailField(help_text='Dirección generada: amazon_x7k2@dockershield.lat', max_length=254, unique=True),
        ),
    ]
