# Generated by Django 5.2.13 on 2026-06-12 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(db_column='id_alias', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='etiqueta', help_text='Etiqueta: ej. Amazon, Foro Reddit', max_length=100)),
                ('address', models.EmailField(db_column='direccion', help_text='Dirección generada: amazon_x7k2@dockershield.lat', max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('destroyed_at', models.DateTimeField(blank=True, db_column='destruido_en', null=True)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Alias',
                'db_table': 'tbl_alias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AliasQuotaRequest',
            fields=[
                ('id', models.AutoField(db_column='id_solicitud_cupo', primary_key=True, serialize=False)),
                ('requested_amount', models.PositiveIntegerField(db_column='cantidad_solicitada', help_text='Cuántos alias EXTRA pide el usuario (1-10).')),
                ('reason', models.TextField(blank=True, db_column='motivo', help_text='Justificación opcional del usuario.')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_column='estado', default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, db_column='nota_admin', help_text='Nota del admin al aprobar/rechazar (opcional).')),
                ('granted_amount', models.PositiveIntegerField(db_column='cantidad_concedida', default=0, help_text='Cuánto le concedió el admin al aprobar. 0 si fue rechazada.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('resolved_at', models.DateTimeField(blank=True, db_column='resuelto_en', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('resolved_by', models.ForeignKey(blank=True, db_column='id_resuelto_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alias_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='alias_quota_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de cupo de alias',
                'verbose_name_plural': 'Solicitudes de cupo de alias',
                'db_table': 'tbl_solicitud_cupo_alias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tbl_solicit_estado_55a07e_idx'), models.Index(fields=['user', '-created_at'], name='tbl_solicit_id_usua_616a05_idx')],
            },
        ),
    ]
