# Generated by Django 5.2.13 on 2026-05-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasQuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.PositiveIntegerField(help_text='Cuántos alias EXTRA pide el usuario (1-10).')),
                ('reason', models.TextField(blank=True, help_text='Justificación opcional del usuario.')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Nota del admin al aprobar/rechazar (opcional).')),
                ('granted_amount', models.PositiveIntegerField(default=0, help_text='Cuánto le concedió el admin al aprobar. 0 si fue rechazada.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alias_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_quota_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de cupo de alias',
                'verbose_name_plural': 'Solicitudes de cupo de alias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='aliases_ali_status_b36bcd_idx'), models.Index(fields=['user', '-created_at'], name='aliases_ali_user_id_77a675_idx')],
            },
        ),
    ]
