# Generated by Django 5.2.13 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='address',
            field=models.EmailField(db_column='ali_direccion', help_text='Dirección generada: amazon_x7k2@dockershield.lat', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ali_creado_en'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, db_column='ali_destruido_en', null=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='is_active',
            field=models.BooleanField(db_column='ali_activo', default=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='label',
            field=models.CharField(db_column='ali_etiqueta', help_text='Etiqueta: ej. Amazon, Foro Reddit', max_length=100),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='admin_note',
            field=models.TextField(blank=True, db_column='sca_nota_admin', help_text='Nota del admin al aprobar/rechazar (opcional).'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='sca_creado_en'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='granted_amount',
            field=models.PositiveIntegerField(db_column='sca_cantidad_concedida', default=0, help_text='Cuánto le concedió el admin al aprobar. 0 si fue rechazada.'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='id',
            field=models.AutoField(db_column='id_solicitud_cupo_alias', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='is_active',
            field=models.BooleanField(db_column='sca_activo', default=True),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='reason',
            field=models.TextField(blank=True, db_column='sca_motivo', help_text='Justificación opcional del usuario.'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='requested_amount',
            field=models.PositiveIntegerField(db_column='sca_cantidad_solicitada', help_text='Cuántos alias EXTRA pide el usuario (1-10).'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_column='sca_resuelto_en', null=True),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_column='sca_estado', default='pending', max_length=10),
        ),
    ]
