# Generated by Django 5.2.13 on 2026-06-04 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0002_aliasquotarequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aliasquotarequest',
            new_name='tbl_solicit_estado_55a07e_idx',
            old_name='aliases_ali_status_b36bcd_idx',
        ),
        migrations.RenameIndex(
            model_name='aliasquotarequest',
            new_name='tbl_solicit_id_usua_616a05_idx',
            old_name='aliases_ali_user_id_77a675_idx',
        ),
        migrations.AddField(
            model_name='aliasquotarequest',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='address',
            field=models.EmailField(db_column='direccion', help_text='Dirección generada: amazon_x7k2@dockershield.lat', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, db_column='destruido_en', null=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='id',
            field=models.AutoField(db_column='id_alias', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alias',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='alias',
            name='label',
            field=models.CharField(db_column='etiqueta', help_text='Etiqueta: ej. Amazon, Foro Reddit', max_length=100),
        ),
        migrations.AlterField(
            model_name='alias',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='admin_note',
            field=models.TextField(blank=True, db_column='nota_admin', help_text='Nota del admin al aprobar/rechazar (opcional).'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='granted_amount',
            field=models.PositiveIntegerField(db_column='cantidad_concedida', default=0, help_text='Cuánto le concedió el admin al aprobar. 0 si fue rechazada.'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='id',
            field=models.AutoField(db_column='id_solicitud_cupo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='reason',
            field=models.TextField(blank=True, db_column='motivo', help_text='Justificación opcional del usuario.'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='requested_amount',
            field=models.PositiveIntegerField(db_column='cantidad_solicitada', help_text='Cuántos alias EXTRA pide el usuario (1-10).'),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_column='resuelto_en', null=True),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_column='id_resuelto_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alias_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], db_column='estado', default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='aliasquotarequest',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='alias_quota_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='alias',
            table='tbl_alias',
        ),
        migrations.AlterModelTable(
            name='aliasquotarequest',
            table='tbl_solicitud_cupo_alias',
        ),
    ]
