# Generated by Django 5.2.7 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0002_rename_tbl_solicit_estado_55a07e_idx_tbl_solicit_sca_est_c8795d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='is_active',
            field=models.BooleanField(db_column='ali_activo', db_index=True, default=True),
        ),
    ]
