# Generated by Django 5.2.7 on 2026-06-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0003_add_perf_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1;",
            elidable=True,
            state_operations=[
                migrations.RenameIndex(
                    model_name='aliasquotarequest',
                    new_name='aliases_ali_status_b36bcd_idx',
                    old_name='tbl_solicit_estado_55a07e_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            "SELECT 1;",
            elidable=True,
            state_operations=[
                migrations.RenameIndex(
                    model_name='aliasquotarequest',
                    new_name='aliases_ali_user_id_77a675_idx',
                    old_name='tbl_solicit_id_usua_616a05_idx',
                ),
            ],
        ),
    ]
