# Generated by Django 5.2.7 on 2026-06-17 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0004_rename_tbl_solicit_estado_55a07e_idx_aliases_ali_status_b36bcd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['user', '-created_at'], name='aliases_alias_user_created_idx'),
        ),
    ]
