# Generated by Django 5.2.13 on 2026-06-12 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='id_notificacion', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('forward_request', 'Pendiente de aprobación'), ('forwarded', 'Reenviado'), ('threat_alert', 'Amenaza bloqueada'), ('system', 'Sistema')], db_column='tipo', default='system', max_length=20)),
                ('title', models.CharField(db_column='titulo', max_length=200)),
                ('message', models.TextField(blank=True, db_column='mensaje', help_text='Preview corto, opcional')),
                ('read', models.BooleanField(db_column='leido', default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada — reenviada'), ('discarded', 'Descartada'), ('expired', 'Expirada'), ('done', 'Completada')], db_column='estado', default='done', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actioned_at', models.DateTimeField(blank=True, db_column='accionado_en', help_text='Cuándo el usuario tomó acción', null=True)),
                ('target_url', models.CharField(blank=True, db_column='url_destino', default='', max_length=300)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('related_email', models.ForeignKey(blank=True, db_column='id_correo_relacionado', help_text='Si la notificación es sobre un correo concreto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mail.emailmessage')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'tbl_notificacion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tbl_notific_id_usua_1fffbc_idx'), models.Index(fields=['user', 'read'], name='tbl_notific_id_usua_f2ef9a_idx')],
            },
        ),
    ]
