# Generated by Django 5.2.13 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actioned_at',
            field=models.DateTimeField(blank=True, db_column='ntf_accionado_en', help_text='Cuándo el usuario tomó acción', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ntf_creado_en'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_column='ntf_activo', default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, db_column='ntf_mensaje', help_text='Preview corto, opcional'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_column='ntf_leido', default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada — reenviada'), ('discarded', 'Descartada'), ('expired', 'Expirada'), ('done', 'Completada')], db_column='ntf_estado', default='done', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, db_column='ntf_url_destino', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_column='ntf_titulo', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('forward_request', 'Pendiente de aprobación'), ('forwarded', 'Reenviado'), ('threat_alert', 'Amenaza bloqueada'), ('system', 'Sistema')], db_column='ntf_tipo', default='system', max_length=20),
        ),
    ]
