# Generated by Django 5.2.7 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_tbl_notific_id_usua_1fffbc_idx_tbl_notific_id_usua_770a85_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_column='ntf_leido', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada — reenviada'), ('discarded', 'Descartada'), ('expired', 'Expirada'), ('done', 'Completada')], db_column='ntf_estado', db_index=True, default='done', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('forward_request', 'Pendiente de aprobación'), ('forwarded', 'Reenviado'), ('threat_alert', 'Amenaza bloqueada'), ('system', 'Sistema')], db_column='ntf_tipo', db_index=True, default='system', max_length=20),
        ),
    ]
