# Generated by Django 5.2.13 on 2026-06-04 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_draft_is_active_emailmessage_is_active_and_more'),
        ('notifications', '0002_notification_target_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='tbl_notific_id_usua_1fffbc_idx',
            old_name='notificatio_user_id_05b4bc_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='tbl_notific_id_usua_f2ef9a_idx',
            old_name='notificatio_user_id_878a13_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actioned_at',
            field=models.DateTimeField(blank=True, db_column='accionado_en', help_text='Cuándo el usuario tomó acción', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(db_column='id_notificacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, db_column='mensaje', help_text='Preview corto, opcional'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_column='leido', default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_email',
            field=models.ForeignKey(blank=True, db_column='id_correo_relacionado', help_text='Si la notificación es sobre un correo concreto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mail.emailmessage'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada — reenviada'), ('discarded', 'Descartada'), ('expired', 'Expirada'), ('done', 'Completada')], db_column='estado', default='done', max_length=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, db_column='url_destino', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_column='titulo', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('forward_request', 'Pendiente de aprobación'), ('forwarded', 'Reenviado'), ('threat_alert', 'Amenaza bloqueada'), ('system', 'Sistema')], db_column='tipo', default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='tbl_notificacion',
        ),
    ]
