# Generated by Django 5.2.7 on 2026-06-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_perf_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1;",
            elidable=True,
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='notificatio_user_id_05b4bc_idx',
                    old_name='tbl_notific_id_usua_1fffbc_idx',
                ),
            ],
        ),
        migrations.RunSQL(
            "SELECT 1;",
            elidable=True,
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='notificatio_user_id_878a13_idx',
                    old_name='tbl_notific_id_usua_f2ef9a_idx',
                ),
            ],
        ),
    ]
