# Generated by Django 5.2.13 on 2026-06-12 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aliases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(db_column='id_borrador', primary_key=True, serialize=False)),
                ('to_email', models.CharField(blank=True, db_column='destinatarios', max_length=255)),
                ('subject', models.CharField(blank=True, db_column='asunto', max_length=255)),
                ('body_html', models.TextField(blank=True, db_column='cuerpo_html')),
                ('scheduled_at', models.DateTimeField(blank=True, db_column='programado_en', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='actualizado_en', db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='eliminado_en', db_index=True, null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('alias', models.ForeignKey(blank=True, db_column='id_alias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='aliases.alias')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrador',
                'verbose_name_plural': 'Borradores',
                'db_table': 'tbl_borrador',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(db_column='id_mensaje_correo', primary_key=True, serialize=False)),
                ('from_email', models.EmailField(db_column='correo_remitente', max_length=254)),
                ('subject', models.CharField(db_column='asunto', max_length=255)),
                ('body', models.TextField(blank=True, db_column='cuerpo', help_text='Cuerpo en texto plano (para preview y análisis)')),
                ('body_html', models.TextField(blank=True, db_column='cuerpo_html', help_text='HTML neutralizado (links/imágenes bloqueados - se muestra en la bandeja)')),
                ('body_html_raw', models.TextField(blank=True, db_column='cuerpo_html_original', help_text='HTML ORIGINAL sin neutralizar (se usa al reenviar al correo real)')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_column='recibido_en')),
                ('read', models.BooleanField(db_column='leido', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='eliminado_en', db_index=True, help_text='Si está seteado, el correo está en papelera', null=True)),
                ('risk_score', models.IntegerField(db_column='puntaje_riesgo', default=0, help_text='0-100. 0=seguro, 100=malware')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('alias', models.ForeignKey(db_column='id_alias', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='aliases.alias')),
            ],
            options={
                'verbose_name': 'Correo recibido',
                'verbose_name_plural': 'Correos recibidos',
                'db_table': 'tbl_mensaje_correo',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAuthVerdict',
            fields=[
                ('id', models.AutoField(db_column='id_verificacion_correo', primary_key=True, serialize=False)),
                ('auth_verdict', models.CharField(blank=True, choices=[('verified', 'Verificado criptográficamente'), ('unverified', 'Sin verificar'), ('spoofed', 'Suplantación detectada')], db_column='veredicto_auth', default='unverified', max_length=12)),
                ('auth_spf', models.CharField(blank=True, db_column='auth_spf', help_text='pass / fail / softfail / neutral / none', max_length=10)),
                ('auth_dkim', models.CharField(blank=True, db_column='auth_dkim', help_text='pass / fail / none', max_length=10)),
                ('auth_dmarc', models.CharField(blank=True, db_column='auth_dmarc', help_text='pass / fail / none', max_length=10)),
                ('auth_signed_by', models.CharField(blank=True, db_column='firmado_por', help_text='Dominio que firmó con DKIM (header.d=)', max_length=120)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('email', models.OneToOneField(db_column='id_mensaje_correo', on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='mail.emailmessage')),
            ],
            options={
                'db_table': 'tbl_verificacion_correo',
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(db_column='id_adjunto_correo', primary_key=True, serialize=False)),
                ('has_attachment', models.BooleanField(db_column='tiene_adjunto', default=False)),
                ('attachment_name', models.CharField(blank=True, db_column='nombre_adjunto', max_length=255)),
                ('attachment_path', models.CharField(blank=True, db_column='ruta_adjunto', max_length=500)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('email', models.OneToOneField(db_column='id_mensaje_correo', on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='mail.emailmessage')),
            ],
            options={
                'db_table': 'tbl_adjunto_correo',
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.AutoField(db_column='id_correo_enviado', primary_key=True, serialize=False)),
                ('to_email', models.CharField(db_column='destinatarios', max_length=2500)),
                ('subject', models.CharField(blank=True, db_column='asunto', max_length=255)),
                ('body_html', models.TextField(blank=True, db_column='cuerpo_html', help_text='HTML enviado (ya saneado)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='enviado_en')),
                ('scheduled_at', models.DateTimeField(blank=True, db_column='programado_en', help_text='Para envíos programados (send_at SendGrid)', null=True)),
                ('attachments_count', models.IntegerField(db_column='cantidad_adjuntos', default=0)),
                ('attachments_meta', models.JSONField(blank=True, db_column='metadatos_adjuntos', default=list)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='eliminado_en', db_index=True, help_text='Si está seteado, el correo está en papelera', null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('alias', models.ForeignKey(db_column='id_alias', on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='aliases.alias')),
            ],
            options={
                'verbose_name': 'Correo enviado',
                'verbose_name_plural': 'Correos enviados',
                'db_table': 'tbl_correo_enviado',
                'ordering': ['-sent_at'],
            },
        ),
    ]
