# Generated by Django 5.2.13 on 2026-04-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aliases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, help_text='Cuerpo en texto plano (para preview y análisis)')),
                ('body_html', models.TextField(blank=True, help_text='HTML neutralizado (links/imágenes bloqueados — se muestra en la bandeja)')),
                ('body_html_raw', models.TextField(blank=True, help_text='HTML ORIGINAL sin neutralizar (se usa al reenviar al correo real)')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100. 0=seguro, 100=malware')),
                ('auth_verdict', models.CharField(blank=True, choices=[('verified', 'Verificado criptográficamente'), ('unverified', 'Sin verificar'), ('spoofed', 'Suplantación detectada')], default='unverified', max_length=12)),
                ('auth_spf', models.CharField(blank=True, help_text='pass / fail / softfail / neutral / none', max_length=10)),
                ('auth_dkim', models.CharField(blank=True, help_text='pass / fail / none', max_length=10)),
                ('auth_dmarc', models.CharField(blank=True, help_text='pass / fail / none', max_length=10)),
                ('auth_signed_by', models.CharField(blank=True, help_text='Dominio que firmó con DKIM (header.d=)', max_length=120)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='aliases.alias')),
            ],
            options={
                'verbose_name': 'Correo recibido',
                'verbose_name_plural': 'Correos recibidos',
                'ordering': ['-received_at'],
            },
        ),
    ]
