# Generated by Django 5.2.13 on 2026-05-01 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'Mensaje de correo', 'verbose_name_plural': 'Mensajes de correo'},
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Recibido'), ('outbound', 'Enviado')], db_index=True, default='inbound', max_length=10),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.emailmessage'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='to_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
