# Generated by Django 5.2.13 on 2026-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='body_html',
            field=models.TextField(blank=True, db_column='brd_cuerpo_html'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='brd_creado_en'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='brd_eliminado_en', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='is_active',
            field=models.BooleanField(db_column='brd_activo', default=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_column='brd_programado_en', null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='subject',
            field=models.CharField(blank=True, db_column='brd_asunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='to_email',
            field=models.CharField(blank=True, db_column='brd_destinatarios', max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='brd_actualizado_en', db_index=True),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment_name',
            field=models.CharField(blank=True, db_column='ajc_nombre_adjunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='attachment_path',
            field=models.CharField(blank=True, db_column='ajc_ruta_adjunto', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='has_attachment',
            field=models.BooleanField(db_column='ajc_tiene_adjunto', default=False),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='is_active',
            field=models.BooleanField(db_column='ajc_activo', default=True),
        ),
        migrations.AlterField(
            model_name='emailauthverdict',
            name='auth_dkim',
            field=models.CharField(blank=True, db_column='vrc_auth_dkim', help_text='pass / fail / none', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailauthverdict',
            name='auth_dmarc',
            field=models.CharField(blank=True, db_column='vrc_auth_dmarc', help_text='pass / fail / none', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailauthverdict',
            name='auth_signed_by',
            field=models.CharField(blank=True, db_column='vrc_firmado_por', help_text='Dominio que firmó con DKIM (header.d=)', max_length=120),
        ),
        migrations.AlterField(
            model_name='emailauthverdict',
            name='auth_spf',
            field=models.CharField(blank=True, db_column='vrc_auth_spf', help_text='pass / fail / softfail / neutral / none', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailauthverdict',
            name='auth_verdict',
            field=models.CharField(blank=True, choices=[('verified', 'Verificado criptográficamente'), ('unverified', 'Sin verificar'), ('spoofed', 'Suplantación detectada')], db_column='vrc_veredicto_auth', default='unverified', max_length=12),
        ),
        migrations.AlterField(
            model_name='emailauthverdict',
            name='is_active',
            field=models.BooleanField(db_column='vrc_activo', default=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True, db_column='msc_cuerpo', help_text='Cuerpo en texto plano (para preview y análisis)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, db_column='msc_cuerpo_html', help_text='HTML neutralizado (links/imágenes bloqueados - se muestra en la bandeja)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html_raw',
            field=models.TextField(blank=True, db_column='msc_cuerpo_html_original', help_text='HTML ORIGINAL sin neutralizar (se usa al reenviar al correo real)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='msc_eliminado_en', db_index=True, help_text='Si está seteado, el correo está en papelera', null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.EmailField(db_column='msc_correo_remitente', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='is_active',
            field=models.BooleanField(db_column='msc_activo', default=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='read',
            field=models.BooleanField(db_column='msc_leido', default=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_column='msc_recibido_en'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='risk_score',
            field=models.IntegerField(db_column='msc_puntaje_riesgo', default=0, help_text='0-100. 0=seguro, 100=malware'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(db_column='msc_asunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='attachments_count',
            field=models.IntegerField(db_column='cre_cantidad_adjuntos', default=0),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='attachments_meta',
            field=models.JSONField(blank=True, db_column='cre_metadatos_adjuntos', default=list),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='body_html',
            field=models.TextField(blank=True, db_column='cre_cuerpo_html', help_text='HTML enviado (ya saneado)'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='cre_eliminado_en', db_index=True, help_text='Si está seteado, el correo está en papelera', null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='is_active',
            field=models.BooleanField(db_column='cre_activo', default=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_column='cre_programado_en', help_text='Para envíos programados (send_at SendGrid)', null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_column='cre_enviado_en'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='subject',
            field=models.CharField(blank=True, db_column='cre_asunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='to_email',
            field=models.CharField(db_column='cre_destinatarios', max_length=2500),
        ),
    ]
