# Generated by Django 5.2.13 on 2026-05-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_emailmessage_options_emailmessage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'Correo recibido', 'verbose_name_plural': 'Correos recibidos'},
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='in_reply_to',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='to_email',
        ),
    ]
