# Generated by Django 5.2.13 on 2026-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_draft_body_html_alter_draft_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_column='cre_programado_en', help_text='Para envíos programados', null=True),
        ),
    ]
