# Generated by Django 5.2.7 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_sentemail_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='read',
            field=models.BooleanField(db_column='msc_leido', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_column='msc_recibido_en', db_index=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='risk_score',
            field=models.IntegerField(db_column='msc_puntaje_riesgo', db_index=True, default=0, help_text='0-100. 0=seguro, 100=malware'),
        ),
    ]
