# Generated by Django 5.2.7 on 2026-06-17 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0005_alias_aliases_alias_user_created_idx'),
        ('mail', '0004_add_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['user', 'deleted_at'], name='mail_draft_user_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['alias', 'deleted_at', '-received_at'], name='mail_msg_alias_del_rcv_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['alias', 'risk_score'], name='mail_msg_alias_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='sentemail',
            index=models.Index(fields=['-sent_at'], name='mail_sentemail_sent_at_idx'),
        ),
        migrations.AddIndex(
            model_name='sentemail',
            index=models.Index(fields=['alias', '-sent_at'], name='mail_sentemail_alias_sent_idx'),
        ),
    ]
