# Generated by Django 5.2.13 on 2026-05-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0001_initial'),
        ('mail', '0004_alter_emailmessage_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True, help_text='HTML enviado (ya saneado)')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Para envíos programados (send_at SendGrid)', null=True)),
                ('attachments_count', models.IntegerField(default=0)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='aliases.alias')),
            ],
            options={
                'verbose_name': 'Correo enviado',
                'verbose_name_plural': 'Correos enviados',
                'ordering': ['-sent_at'],
            },
        ),
    ]
