# Generated by Django 5.2.13 on 2026-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Si está seteado, el correo está en papelera', null=True),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Si está seteado, el correo está en papelera', null=True),
        ),
    ]
