# Generated by Django 5.2.7 on 2026-06-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_draft_mail_draft_user_deleted_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='resend_email_id',
            field=models.CharField(blank=True, db_column='msc_id_resend', help_text='ID único del correo en Resend (para deduplicar webhooks)', max_length=255, null=True, unique=True),
        ),
    ]
