# Generated by Django 5.2.13 on 2026-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
