# Generated by Django 5.2.13 on 2026-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_draft_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='attachments_meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
