# Generated by Django 5.2.13 on 2026-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_sentemail_attachments_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='to_email',
            field=models.CharField(max_length=2500),
        ),
    ]
