# Generated by Django 5.2.13 on 2026-06-04 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliases', '0003_rename_aliases_ali_status_b36bcd_idx_tbl_solicit_estado_55a07e_idx_and_more'),
        ('mail', '0010_alter_sentemail_to_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='is_active',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='alias',
            field=models.ForeignKey(blank=True, db_column='id_alias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='aliases.alias'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='body_html',
            field=models.TextField(blank=True, db_column='cuerpo_html'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='eliminado_en', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.AutoField(db_column='id_borrador', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='draft',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_column='programado_en', null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='subject',
            field=models.CharField(blank=True, db_column='asunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='to_email',
            field=models.CharField(blank=True, db_column='destinatarios', max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='actualizado_en', db_index=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='user',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='alias',
            field=models.ForeignKey(db_column='id_alias', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='aliases.alias'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='attachment_name',
            field=models.CharField(blank=True, db_column='nombre_adjunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='attachment_path',
            field=models.CharField(blank=True, db_column='ruta_adjunto', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='auth_dkim',
            field=models.CharField(blank=True, db_column='auth_dkim', help_text='pass / fail / none', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='auth_dmarc',
            field=models.CharField(blank=True, db_column='auth_dmarc', help_text='pass / fail / none', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='auth_signed_by',
            field=models.CharField(blank=True, db_column='firmado_por', help_text='Dominio que firmó con DKIM (header.d=)', max_length=120),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='auth_spf',
            field=models.CharField(blank=True, db_column='auth_spf', help_text='pass / fail / softfail / neutral / none', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='auth_verdict',
            field=models.CharField(blank=True, choices=[('verified', 'Verificado criptográficamente'), ('unverified', 'Sin verificar'), ('spoofed', 'Suplantación detectada')], db_column='veredicto_auth', default='unverified', max_length=12),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True, db_column='cuerpo', help_text='Cuerpo en texto plano (para preview y análisis)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, db_column='cuerpo_html', help_text='HTML neutralizado (links/imágenes bloqueados — se muestra en la bandeja)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html_raw',
            field=models.TextField(blank=True, db_column='cuerpo_html_original', help_text='HTML ORIGINAL sin neutralizar (se usa al reenviar al correo real)'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='eliminado_en', db_index=True, help_text='Si está seteado, el correo está en papelera', null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='from_email',
            field=models.EmailField(db_column='correo_remitente', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='has_attachment',
            field=models.BooleanField(db_column='tiene_adjunto', default=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='id',
            field=models.AutoField(db_column='id_mensaje_correo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='read',
            field=models.BooleanField(db_column='leido', default=False),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_column='recibido_en'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='risk_score',
            field=models.IntegerField(db_column='puntaje_riesgo', default=0, help_text='0-100. 0=seguro, 100=malware'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(db_column='asunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='alias',
            field=models.ForeignKey(db_column='id_alias', on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='aliases.alias'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='attachments_count',
            field=models.IntegerField(db_column='cantidad_adjuntos', default=0),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='attachments_meta',
            field=models.JSONField(blank=True, db_column='metadatos_adjuntos', default=list),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='body_html',
            field=models.TextField(blank=True, db_column='cuerpo_html', help_text='HTML enviado (ya saneado)'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='eliminado_en', db_index=True, help_text='Si está seteado, el correo está en papelera', null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='id',
            field=models.AutoField(db_column='id_correo_enviado', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_column='programado_en', help_text='Para envíos programados (send_at SendGrid)', null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_column='enviado_en'),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='subject',
            field=models.CharField(blank=True, db_column='asunto', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='to_email',
            field=models.CharField(db_column='destinatarios', max_length=2500),
        ),
        migrations.AlterModelTable(
            name='draft',
            table='tbl_borrador',
        ),
        migrations.AlterModelTable(
            name='emailmessage',
            table='tbl_mensaje_correo',
        ),
        migrations.AlterModelTable(
            name='sentemail',
            table='tbl_correo_enviado',
        ),
    ]
