# Generated by Django 5.2.13 on 2026-06-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_draft_is_active_emailmessage_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='attachment_path',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='auth_dkim',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='auth_dmarc',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='auth_signed_by',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='auth_spf',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='auth_verdict',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='has_attachment',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, db_column='cuerpo_html', help_text='HTML neutralizado (links/imágenes bloqueados - se muestra en la bandeja)'),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(db_column='id_adjunto_correo', primary_key=True, serialize=False)),
                ('has_attachment', models.BooleanField(db_column='tiene_adjunto', default=False)),
                ('attachment_name', models.CharField(blank=True, db_column='nombre_adjunto', max_length=255)),
                ('attachment_path', models.CharField(blank=True, db_column='ruta_adjunto', max_length=500)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('email', models.OneToOneField(db_column='id_mensaje_correo', on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='mail.emailmessage')),
            ],
            options={
                'db_table': 'tbl_adjunto_correo',
            },
        ),
        migrations.CreateModel(
            name='EmailAuthVerdict',
            fields=[
                ('id', models.AutoField(db_column='id_verificacion_correo', primary_key=True, serialize=False)),
                ('auth_verdict', models.CharField(blank=True, choices=[('verified', 'Verificado criptográficamente'), ('unverified', 'Sin verificar'), ('spoofed', 'Suplantación detectada')], db_column='veredicto_auth', default='unverified', max_length=12)),
                ('auth_spf', models.CharField(blank=True, db_column='auth_spf', help_text='pass / fail / softfail / neutral / none', max_length=10)),
                ('auth_dkim', models.CharField(blank=True, db_column='auth_dkim', help_text='pass / fail / none', max_length=10)),
                ('auth_dmarc', models.CharField(blank=True, db_column='auth_dmarc', help_text='pass / fail / none', max_length=10)),
                ('auth_signed_by', models.CharField(blank=True, db_column='firmado_por', help_text='Dominio que firmó con DKIM (header.d=)', max_length=120)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('email', models.OneToOneField(db_column='id_mensaje_correo', on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='mail.emailmessage')),
            ],
            options={
                'db_table': 'tbl_verificacion_correo',
            },
        ),
    ]
